burndown_for_what/urls.py
# -*- coding: utf8 -*-
# vim: ts=4 sts=4 sw=4 et:

from django.conf.urls import include, url
from django.contrib import admin
from burndown_for_what.views import BurndownTemplateView, SprintView, SprintDetailView, MilestoneView, IssueView


urlpatterns = [
    url(
        r'^sprint/(?P<sprint_id>\d+)/$',
        BurndownTemplateView.as_view(),
        name='burndown_sprint'
    ),
    url(
        r'^api/sprint/$',
        SprintView.as_view(),
        name='api_sprint'
    ),
    url(
        r'^api/sprint/(?P<sprint_id>\d+)/$',
        SprintDetailView.as_view(),
        name='burndown_sprint'
    ),
    url(
        r'^api/milestones/$',
        MilestoneView.as_view(),
        name='api_milestones'
    ),
    url(
        r'^api/issues/(?P<milestone>\w+)/$',
        IssueView.as_view(),
        name='api_milestones'
    ),
]

burndown_for_what/models.py
# -*- coding: utf8 -*-
# vim: ts=4 sts=4 sw=4 et:

from django.db import models

from burndown_for_what.utils import SPRINT_POINT, connect_github


class Organization(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return u'{}'.format(self.name)


class Team(models.Model):
    name = models.CharField(max_length=150)
    persons = models.ManyToManyField('auth.User')

    def __str__(self):
        return u'{}'.format(self.name)


class Sprint(models.Model):
    name = models.CharField(max_length=150)
    scrum_master = models.ForeignKey('auth.User')
    team = models.ForeignKey('burndown_for_what.Team')
    resume = models.TextField(null=True, blank=True, help_text=u'Markdown is possible.')
    date_begin = models.DateField()
    github_user = models.CharField(max_length=150, blank=True, null=True)
    github_repo = models.CharField(max_length=150, blank=True, null=True)
    github_milestone_id = models.IntegerField(default=0)
    closed = models.BooleanField()

    def __str__(self):
        return u'{}'.format(self.name)

    def _update_daily(self):
        issues_closed = self.issue_set.filter(state='closed')
        for daily in self.daily_set.all():
            issues_daily = issues_closed.filter(closed_at=daily.date)
            if issues_daily:
                daily.score = sum(issues_daily.filter(unplanned=False).values_list('score', flat=True))
                daily.score_unplanned = sum(issues_daily.filter(unplanned=True).values_list('score', flat=True))
                daily.save()

    def _create_issue(self, issue):
        """
        Create model Issues with data from GitHub.

        :param Issue issue:
        :return:
        """
        unplanned = any([label for label in issue.labels if label.name == 'unplanned'])
        score = sum([float(label.name) for label in issue.labels if label.name in SPRINT_POINT])
        assignee = issue.assignee.login if issue.assignee else None
        return Issue.objects.create(
            sprint=self,
            title=issue.title,
            github_id=issue.id,
            url=issue.html_url,
            number=issue.number,
            state=issue.state,
            assignee_login=assignee,
            closed_at=issue.closed_at,
            score=score,
            unplanned=unplanned
        )

    def save(self, *args, **kwargs):
        """
        Save object and search/create issues refers the milestone, after this, update *dailys*

        :return:
        """
        connection = connect_github(self.github_user, self.github_repo)
        Issue.objects.filter(sprint=self).delete()
        super(Sprint, self).save(*args, **kwargs)
        for issue in connection.issues.list_by_repo(state='all', **{'milestone': self.github_milestone_id}).all():
            issue_created = self._create_issue(issue)
            for assignee in issue.assignees:
                Assignee.objects.create(issue=issue_created, login=assignee['login'])
        self._update_daily()

    @property
    def duration(self):
        return self.daily_set.count()

    @property
    def score_unplanned(self):
        return sum(self.issue_set.filter(unplanned=True, state='closed').values_list('score', flat=True))

    @property
    def scored(self):
        return sum(self.issue_set.filter(unplanned=False, state='closed').values_list('score', flat=True))

    @property
    def percentage_reached(self):
        return (self.scored * 100) / self.score

    @property
    def score(self):
        return sum(self.issue_set.filter(unplanned=False).values_list('score', flat=True))

    @property
    def issues_count(self):
        return self.issue_set.count()

    @property
    def avg_score(self):
        return self.score / self.duration

    @staticmethod
    def burndown_point(score, index, avg_score):
        return score - (index * avg_score)

    def chart_data(self):
        """
        Returns need data for ploting chart.

        :return dict:
        """
        # create local variables for avoid hints on Database.
        score = self.score
        score_daily = 0
        score_unplanned = 0
        score_per_day = self.avg_score

        result = {
            'days': [self.date_begin,],
            'burndown_line': [score,],
            'score': [score,],
            'unplanned': [0,],
        }
        for x, daily in enumerate(self.daily_set.all(), start=1):
            result['days'].append(str(daily.date))
            result['burndown_line'].append(Sprint.burndown_point(score, x, score_per_day))
            if daily.closed:
                score_unplanned += daily.score_unplanned if daily.score_unplanned else 0
                score_daily += daily.score if daily.score else 0
                result['score'].append(score - score_daily)
                result['unplanned'].append(score_unplanned)
        return result


class Issue(models.Model):
    sprint = models.ForeignKey('burndown_for_what.Sprint')
    title = models.TextField()
    github_id = models.IntegerField(default=0)
    url = models.TextField()
    number = models.IntegerField(default=0)
    state = models.CharField(max_length=150, blank=True, null=True)
    assignee_login = models.CharField(max_length=150, blank=True, null=True)
    closed_at = models.DateField(null=True, blank=True)
    score = models.FloatField(null=True, blank=True)
    unplanned = models.NullBooleanField()


class Assignee(models.Model):
    issue = models.ForeignKey('burndown_for_what.Issue')
    login = models.CharField(max_length=150)


class Daily(models.Model):
    sprint = models.ForeignKey('burndown_for_what.Sprint')
    date = models.DateField()
    score = models.FloatField(null=True, blank=True)
    score_unplanned = models.FloatField(null=True, blank=True)
    observation = models.TextField(null=True, blank=True)
    closed = models.BooleanField()

    def __str__(self):
        return u'{}'.format(self.date)

burndown_for_what/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Burndown for what</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700">
  <link rel="stylesheet" href="{% static 'css/burndown_for_what.css' %}">
</head>
<body>
  <nav class="navbar navbar-default c-navbar-base">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="https://cloud.githubusercontent.com/assets/6231505/10681166/4b4d4cce-7905-11e5-9d21-0469ebd11c13.png">
        </a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="#" class="{{ organizations }}">Organizations</a></li>
          <li><a href="#" class="{{ teams }}">Teams</a></li>
          <li><a href="#" class="{{ projects }}">Projects</a></li>
          <li><a href="{% url 'sprint_list' %}" class="{{ sprints }}">Sprints</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block "content" %}
    {% endblock "content" %}
  </div>

  <!-- Scripts -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  {% block "extra_script" %}
  {% endblock "extra_script" %}
</body>
</html>

burndown_for_what/templates/burndown.html
{% extends 'burndown_for_what/base.html' %}

{% block extra_js %}
  <script type="text/javascript">
  var lineChartData = {
      labels : [{% for label in burndown_data.days %}"{{ label }}",{% endfor %}],
      datasets : [
          {
              label: "Burndown Line",
              fillColor : "rgba(255,255,255,0.2)",
              strokeColor : "rgba(165,42,42,1)",
              pointColor : "rgba(165,42,42,1)",
              pointStrokeColor : "#fff",
              pointHighlightFill : "#fff",
              pointHighlightStroke : "rgba(220,220,220,1)",
              data : [{% for point in burndown_data.burndown_line %}"{{ point }}",{% endfor %}],
          },
          {
              label: "Score",
              fillColor : "rgba(151,187,205,0.2)",
              strokeColor : "rgba(151,187,205,1)",
              pointColor : "rgba(151,187,205,1)",
              pointStrokeColor : "#fff",
              pointHighlightFill : "#fff",
              pointHighlightStroke : "rgba(151,187,205,1)",
              data : [{% for point in burndown_data.score %}"{{ point }}",{% endfor %}],
          },
          {
              label: "Unplanned",
              fillColor : "rgba(255,127,0,0.2)",
              strokeColor : "rgba(255,127,0,1)",
              pointColor : "rgba(255,127,0,1)",
              pointStrokeColor : "#fff",
              pointHighlightFill : "#fff",
              pointHighlightStroke : "rgba(255,127,0,1)",
              data : [{% for point in burndown_data.unplanned %}"{{ point }}",{% endfor %}],
          }
      ]
  }
window.onload = function(){
  var ctx = document.getElementById("canvas").getContext("2d");
  window.myLine = new Chart(ctx).Line(lineChartData, {
    responsive: true
  });
}
  </script>
{% endblock %}

{% block content %}


  <div class="bs-component">
    <div class="well well lg">
        <div class="list-group">
          <div class="list-group-item col-xs-3">
            <div class="row-action-primary">
              <span class="mega-octicon octicon-code text-primary-bfw"></span>
            </div>
            <div class="row-content">
              <h4 class="list-group-item-heading">Sprint</h4>
              <p class="list-group-item-text" style="font-weight: bold;">{{ sprint.name }}</p>
            </div>
          </div>

          <div class="list-group-item col-xs-3">
            <div class="row-action-primary">
              <span class="mega-octicon octicon-organization text-primary-bfw"></span>
            </div>
            <div class="row-content">
              <h4 class="list-group-item-heading">Team</h4>
              <p class="list-group-item-text" style="font-weight: bold;">{{ sprint.team.name }}</p>
            </div>
          </div>

          <div class="list-group-item col-xs-3">
            <div class="row-action-primary">
              <span class="mega-octicon octicon-mark-github text-primary-bfw"></span>
            </div>
            <div class="row-content">
              <h4 class="list-group-item-heading">Scrum Master</h4>
              <p class="list-group-item-text" style="font-weight: bold;">{{ sprint.scrum_master.username }}</p>
            </div>
          </div>

          <div class="list-group-item col-xs-3">
            <div class="row-action-primary">
              <span class="mega-octicon octicon-repo text-primary-bfw"></span>
            </div>
            <div class="row-content">
              <h4 class="list-group-item-heading">Repo</h4>
              <p class="list-group-item-text" style="font-weight: bold;">{{ sprint.github_repo }}</p>
            </div>
          </div>
          <div class="list-group-item">
          </div>
        </div>
        <div class="row" style="padding-left: 10px; padding-right: 10px;">
          <h2 style="text-align: center;">Sprint Summary</h2>
          <p>
            {{ sprint.resume }}
          </p>
        </div>

      </div>

    <div class="jumbotron">
      <div>
          <canvas id="canvas" height="450" width="600"></canvas>
      </div>
    </div>
    <div class="row">
     <div class="container text-center col-xs-3">
       <div class="well well-lg">
         <span style="font-weight: bold;">{{ sprint.score|floatformat }}</span>
         <br />
         <span>Total Story</span>
       </div>
     </div>

     <div class="container text-center col-xs-3">
       <div class="well well-lg">
         <span style="font-weight: bold;">{{ sprint.scored|floatformat }} ({{ sprint.percentage_reached|floatformat  }}%)</span>
         <br />
         <span>Completed Story Points</span>
       </div>
     </div>

     <div class="container text-center col-xs-3">
       <div class="well well-lg">
         <span style="font-weight: bold;">{{ sprint.issues_count }}</span>
         <br/>
         <span>Total Issues</span>
       </div>
     </div>

     <div class="container text-center col-xs-3">
       <div class="well well-lg">
         <span style="font-weight: bold;">{{ sprint.score_unplanned|floatformat }}</span>
         <br />
         <span>Unplanned Story Points</span>
       </div>
     </div>
   </div>
 </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title" style="text-align: center;">Issues</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Issue</th>
            <th>Title</th>
            <th>Score</th>
            <th>Assignee</th>
            <th>State</th>
            <th>Close At</th>
          </tr>
        </thead>
        <tbody>
          {% for issue in issues %}
              <tr>

                <td class="col-xs-1">
                  <a href="{{issue.url}}" target="_blank">
                    {{ issue.number }}
                  </a>
                </td>

                <td class="col-xs-5">{{ issue.title }}</td>
                <td class="col-xs-1">{{ issue.score|floatformat }}</td>
                <td class="col-xs-2">{% for assignee in issue.assignee_set.all %}{{ assignee.login }}<br>{% endfor %}</td>

                <td class="col-xs-1">
                    <span class=" {% if issue.state == 'open' %} octicon octicon-issue-opened open {% else %} octicon octicon-issue-closed closed {% endif %}"></span>
                </td>

                <td class="col-xs-2"> {% if issue.closed_at %} {{ issue.closed_at }} {% endif %}</td>
              </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title" style="text-align: center;">Issues Unplanned</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Issue</th>
            <th>Title</th>
            <th>Score</th>
            <th>Assignee</th>
            <th>State</th>
            <th>Close At</th>
          </tr>
        </thead>
        <tbody>
          {% for issue in issues_unplanned %}
            <tr>

              <td class="col-xs-1">
                <a href="{{issue.url}}" target="_blank">
                  {{ issue.number }}
                </a>
              </td>

              <td class="col-xs-5">{{ issue.title }}</td>
              <td class="col-xs-1">{{ issue.score|floatformat }}</td>
              <td class="col-xs-2">{{ issue.assignee_login|default_if_none:"no user" }}</td>

              <td class="col-xs-1">
                <span class=" {% if issue.state == 'open' %} octicon octicon-issue-opened open {% else %} octicon octicon-issue-closed closed {% endif %}"></span>
              </td>

              <td class="col-xs-2"> {% if issue.closed_at %} {{ issue.closed_at }} {% endif %}</td>

            </tr>
          {% endfor %}
        </tbody>
      </div>
    </table>
  </div>
{% endblock %}

burndown_for_what/templates/topbar.html
<div class="row">
  <div class="col-md-12">
    <div class="bs-component">
      <div class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bfw-navbar-collapse" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
              <span><img src="https://cloud.githubusercontent.com/assets/6231505/10681166/4b4d4cce-7905-11e5-9d21-0469ebd11c13.png" alt="burndown_for_what" />Burndown For What</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>